![rmotr](https://user-images.githubusercontent.com/7065401/52071918-bda15380-2562-11e9-828c-7f95297e4a82.png)
<hr style="margin-bottom: 40px;">

<img src="https://user-images.githubusercontent.com/7065401/39118381-910eb0c2-46e9-11e8-81f1-a5b897401c23.jpeg"
    style="width:300px; float: right; margin: 0 40px 40px 40px;"></img>

# Numpy: Numeric computing library

NumPy (Numerical Python) is one of the core packages for numerical computing in Python. Pandas, Matplotlib, Statmodels and many other Scientific libraries rely on NumPy.

NumPy major contributions are:

* Efficient numeric computation with C primitives
* Efficient collections with vectorized operations
* An integrated and natural Linear Algebra API
* A C API for connecting NumPy with libraries written in C, C++, or FORTRAN.

Let's develop on efficiency. In Python, **everything is an object**, which means that even simple ints are also objects, with all the required machinery to make object work. We call them "Boxed Ints". In contrast, NumPy uses primitive numeric types (floats, ints) which makes storing and computation efficient.

<img src="https://docs.google.com/drawings/d/e/2PACX-1vTkDtKYMUVdpfVb3TTpr_8rrVtpal2dOknUUEOu85wJ1RitzHHf5nsJqz1O0SnTt8BwgJjxXMYXyIqs/pub?w=726&h=396" />


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Hands on! 

In [137]:
import sys
import numpy as np

## Basic Numpy Arrays

In [138]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [139]:
# Declare list a
a = np.array([1, 2, 3, 4])

In [140]:
# Declare list b
b = np.array([0, 0.5, 1, 1.5, 2])

In [141]:
# Return first two elements
a[0], a[1]

(np.int64(1), np.int64(2))

In [142]:
# Output all elements list a
a[0:]

array([1, 2, 3, 4])

In [143]:
a[1:3]

array([2, 3])

In [144]:
a[1:-1]

array([2, 3])

In [145]:
#
a[::2]

array([1, 3])

In [146]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [147]:
b[0], b[2], b[-1]

(np.float64(0.0), np.float64(1.0), np.float64(2.0))

In [148]:
b[[0, 2, -1]]

array([0., 1., 2.])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Array Types

In [149]:
a

array([1, 2, 3, 4])

In [150]:
a.dtype

dtype('int64')

In [151]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [152]:
b.dtype

dtype('float64')

In [153]:
np.array([1, 2, 3, 4], dtype=float)

array([1., 2., 3., 4.])

In [154]:
np.array([1, 2, 3, 4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [155]:
c = np.array(["a", "b", "c"])

In [156]:
c.dtype

dtype('<U1')

In [157]:
d = np.array([{"a": 1}, sys])

In [158]:
d.dtype

dtype('O')

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Dimensions and shapes

In [159]:
A = np.array([[1, 2, 3], [4, 5, 6]])

In [160]:
A.shape

(2, 3)

In [161]:
A.ndim

2

In [162]:
A.size

6

In [163]:
B = np.array(
    [
        [
            [12, 11, 10],
            [9, 8, 7],
        ],
        [[6, 5, 4], [3, 2, 1]],
    ]
)

In [164]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [165]:
B.shape

(2, 2, 3)

In [166]:
B.ndim

3

In [167]:
B.size

12

If the shape isn't consistent, it'll just fall back to regular Python objects:

In [168]:
C = np.array(
    [
        [
            [12, 11, 10],
            [9, 8, 7],
        ],
        [[6, 5, 4], [3, 2, 1]],
    ]
)

In [169]:
# data type
C.dtype

dtype('int64')

In [170]:
# architecture of the list
C.shape

(2, 2, 3)

In [171]:
# how many elements in the list
C.size

12

In [172]:
type(C[0])

numpy.ndarray

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Indexing and Slicing of Matrices

In [173]:
# Square matrix
A = np.array(
    [
        # 0. 1. 2
        [1, 2, 3],  # 0
        [4, 5, 6],  # 1
        [7, 8, 9],  # 2
    ]
)

In [174]:
# Second row
A[1]

array([4, 5, 6])

In [175]:
# Option 1: Second row first element
A[1][0]

np.int64(4)

In [176]:
# A[d1, d2, d3, d4]

In [177]:
# Option 2: Second row first element
A[1, 0]

np.int64(4)

In [178]:
# First two rows
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [179]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [180]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [181]:
A[:2, 2:]

array([[3],
       [6]])

In [182]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [183]:
A[1] = np.array([10, 10, 10])

In [184]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [185]:
A[2] = 99

In [186]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Summary statistics

In [187]:
a = np.array([1, 2, 3, 4])

In [188]:
a.sum()

np.int64(10)

In [189]:
a.mean()

np.float64(2.5)

In [190]:
a.std()

np.float64(1.118033988749895)

In [191]:
a.var()

np.float64(1.25)

In [192]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [193]:
A.sum()

np.int64(45)

In [194]:
A.mean()

np.float64(5.0)

In [195]:
A.std()

np.float64(2.581988897471611)

In [196]:
A.sum(axis=0)

array([12, 15, 18])

In [197]:
A.sum(axis=1)

array([ 6, 15, 24])

In [198]:
A.mean(axis=0)

array([4., 5., 6.])

In [199]:
A.mean(axis=1)

array([2., 5., 8.])

In [200]:
A.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [201]:
A.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

And [many more](https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.ndarray.html#array-methods)...

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Broadcasting and Vectorized operations

In [202]:
a = np.arange(4)

In [203]:
a

array([0, 1, 2, 3])

In [204]:
a + 10

array([10, 11, 12, 13])

In [205]:
a * 10

array([ 0, 10, 20, 30])

In [206]:
a

array([0, 1, 2, 3])

In [207]:
a += 100

In [208]:
a

array([100, 101, 102, 103])

In [209]:
l = [0, 1, 2, 3]

In [210]:
[i * 10 for i in l]

[0, 10, 20, 30]

In [211]:
a = np.arange(5)

In [212]:
a + 20

array([20, 21, 22, 23, 24])

In [213]:
a

array([0, 1, 2, 3, 4])

In [214]:
b = np.array([10, 10, 10, 10])

In [215]:
b

array([10, 10, 10, 10])

In [216]:
a + b

ValueError: operands could not be broadcast together with shapes (5,) (4,) 

In [ ]:
a * b

array([ 0, 10, 20, 30])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Boolean arrays
_(Also called masks)_

In [ ]:
a = np.arange(4)

In [ ]:
a

array([0, 1, 2, 3])

In [ ]:
a[0], a[-1]

(np.int64(0), np.int64(3))

In [ ]:
a[[0, -1]]

array([0, 3])

In [ ]:
a[[True, False, False, True]]

array([0, 3])

In [ ]:
a

array([0, 1, 2, 3])

In [ ]:
a >= 2

array([False, False,  True,  True])

In [ ]:
a[a >= 2]

array([2, 3])

In [ ]:
a.mean()

np.float64(1.5)

In [ ]:
a[a > a.mean()]

array([2, 3])

In [ ]:
a[~(a > a.mean())]

array([0, 1])

In [ ]:
a[(a == 0) | (a == 1)]

array([0, 1])

In [ ]:
a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

In [ ]:
A = np.random.randint(100, size=(3, 3))

In [ ]:
A

array([[71, 18, 10],
       [65, 68, 61],
       [ 2, 44, 79]], dtype=int32)

In [ ]:
A[np.array([[True, False, True], [False, True, False], [True, False, True]])]

array([71, 10, 68,  2, 79], dtype=int32)

In [ ]:
A > 30

array([[ True, False, False],
       [ True,  True,  True],
       [False,  True,  True]])

In [ ]:
A[A > 30]

array([71, 65, 68, 61, 44, 79], dtype=int32)

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Linear Algebra

In [ ]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [ ]:
B = np.array([[6, 5], [4, 3], [2, 1]])

In [ ]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [ ]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [ ]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [ ]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Size of objects in Memory

### Int, floats

In [ ]:
# An integer in Python is > 24bytes
sys.getsizeof(1)

28

In [ ]:
# Longs are even larger
sys.getsizeof(10**100)

72

In [ ]:
# Numpy size is much smaller
np.dtype(int).itemsize

8

In [ ]:
# Numpy size is much smaller
np.dtype(np.int8).itemsize

1

In [ ]:
np.dtype(float).itemsize

8

### Lists are even larger

In [ ]:
# A one-element list
sys.getsizeof([1])

64

In [ ]:
# An array of one element in numpy
np.array([1]).nbytes

8

### And performance is also important

In [ ]:
l = list(range(100000))

In [ ]:
a = np.arange(100000)

In [ ]:
%time np.sum(a ** 2)

CPU times: total: 0 ns
Wall time: 785 μs


np.int64(333328333350000)

In [218]:
%time sum([x ** 2 for x in l])

CPU times: total: 0 ns
Wall time: 8.34 μs


14

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Useful Numpy functions

### `random` 

In [ ]:
np.random.random(size=2)

array([0.99020267, 0.82786279])

In [ ]:
np.random.normal(size=2)

array([ 1.30944784, -0.04405478])

In [ ]:
np.random.rand(2, 4)

array([[0.04332564, 0.0718106 , 0.5151989 , 0.7529211 ],
       [0.7904607 , 0.52223962, 0.0144005 , 0.32420849]])

---
### `arange`

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [ ]:
np.arange(0, 1, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

---
### `reshape`

In [ ]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
np.arange(10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

---
### `linspace`

In [ ]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [ ]:
np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

---
### `zeros`, `ones`, `empty`

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.zeros((3, 3), dtype=np.int)

AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

In [ ]:
np.ones(5)

In [ ]:
np.ones((3, 3))

In [ ]:
np.empty(5)

In [ ]:
np.empty((2, 2))

---
### `identity` and `eye`

In [ ]:
np.identity(3)

In [ ]:
np.eye(3, 3)

In [ ]:
np.eye(8, 4)

In [ ]:
np.eye(8, 4, k=1)

In [ ]:
np.eye(8, 4, k=-3)

In [ ]:
"Hello World"[6]

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)